---
name: enable-auto-merge
on:
  workflow_call:
    secrets:
      gh_app_id:
        required: true
      gh_app_private_key:
        required: true
jobs:
  enable-auto-merge:
    # Enable automerge to merge pull requests from Renovate automatically.
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: suzuki-shunsuke/enable-auto-merge-action@2bb7628e1464f57d5c34adcee7d567d3b5897e52 # v0.1.0-5
        with:
          pr_number: ${{github.event.pull_request.number}}
          merge_method: squash
          github_app_id: ${{secrets.gh_app_id}}
          github_app_private_key: ${{secrets.gh_app_private_key}}
