---
name: enable-auto-merge
on:
  workflow_call:
    secrets:
      gh_app_id:
        required: true
      gh_app_private_key:
        required: true
jobs:
  enable-auto-merge:
    # Enable automerge to merge pull requests from Renovate automatically.
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: suzuki-shunsuke/enable-auto-merge-action@717a756c86d5e74a09065ba22bf83511f60981c7 # v0.1.0-4
        with:
          pr_number: ${{github.event.pull_request.number}}
          merge_method: squash
          github_app_id: ${{secrets.gh_app_id}}
          github_app_private_key: ${{secrets.gh_app_private_key}}
